### ISSUE TITLE
User is not notified if they select a file above the file size limit. 

### ISSUE THREAD

**Issue by insomniacmonkey** [nilsjohnson/gif-it#26]
I seem to be hitting an upload limit when trying to upload a file that is above what ever the limit is. 

![limitreached](https://user-images.githubusercontent.com/391495/96068400-99ce9000-0e61-11eb-8b0f-eab24c729117.png)

it also appeared to let the broken link be created and shared on the home page 😢 

![thatsnotright](https://user-images.githubusercontent.com/391495/96068343-6f7cd280-0e61-11eb-8413-9362deb27c36.png)

**Comment by nilsjohnson** [comment]
Ohh nooo :( 

I'm pretty sure what happened here is that the socket associated with your upload disconnected (due to a network error most likely)  and as a result deleted the upload. - The program is built so that if a user navigates to some other page, closes their browser, etc, the upload is deleted with the assumption the user changed their mind. I still need to build socket reconnect functionality. I will add this feature towards the top of the TODO list.

The upload limit is 70mb for any file. The upload should reject video's larger than 70mb but I have yet to try images larger than that.

**Comment by nilsjohnson** [comment]
In the latest PR, I made a change so that a socket can disconnect and reconnect anytime during an upload session. Hopefully this stops this behavior!
